spring.application.name=fiduciaire-backend
server.port=8080

# Configuration Base de données H2 (en mémoire pour le développement)
spring.datasource.url=jdbc:h2:mem:fiduciadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Activer la console H2 (accessible sur /h2-console)
spring.h2.console.enabled=true

# Configuration Email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mehdi123bts@gmail.com
spring.mail.password=gnncoobnippwwpfn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
